backend:
  name: github
  repo: AlexandrFedoseev/roza-shop-blog
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: "Страницы Сайта"
    name: "pages"
    files:
      - label: "Главная"
        name: "home"
        file: "site/content/home/home.yml"
        fields:
          - {label: "СЕО Заголовок", name: title, widget: string}
          - {label: "СЕО Описание", name: description, widget: text}
          - {label: "СЕО Изображение", name: seoimage, widget: image}
          - {label: "Фон заголовка", name: image, widget: image}
          - label: "Примеры работ"
            name: works
            widget: list
            fields:
              - {label: "СЕО подпись", name: alt, widget: string}
              - {label: "Картинка", name: image, widget: image}
          - label: "Преимущества"
            name: cons
            widget: list
            fields:
              - {label: "Пункт", name: point, widget: string}
          - {label: "О нас", name: about, widget: markdown}
          - label: "Инстаграм"
            name: instagram
            widget: list
            fields:
              - {label: "СЕО подпись", name: alt, widget: string}
              - {label: "Картинка", name: image, widget: image}
      - label: "Наши Работы"
        name: "ourWorks"
        file: "site/content/our-works.yml"
        fields:
          - {label: "СЕО Заголовок", name: title, widget: string}
          - {label: "СЕО Описание", name: description, widget: text}
          - {label: "СЕО Изображение", name: image, widget: image}
          - {label: "Фон заголовка", name: image, widget: image}
      - label: "Контакты"
        name: "contacts"
        file: "site/content/contacts.yml"
        fields:
          - {label: "СЕО Заголовок", name: title, widget: string}
          - {label: "СЕО Описание", name: description, widget: text}
          - {label: "СЕО Изображение", name: seoimage, widget: image}
          - {label: "Фон заголовка", name: image, widget: image}
          - {label: "Телефон 1", name: phone1, widget: string}
          - {label: "Телефон 2", name: phone2, widget: string}
          - {label: "Адрес", name: location, widget: string}
          - {label: "ГЕО lat", name: lat, widget: number}
          - {label: "ГЕО lon", name: lon, widget: number}
          - {label: "Время работы", name: worktime, widget: string}
  - name: services
    label: "Услуги"
    folder: site/content/services
    create: true
    fields:
      - { name: path, label: "URL путь" }
      - { name: title, label: "Название" }
      - {label: "Фон заголовка", name: image, widget: image}
      - {label: "СЕО Заголовок", name: seotitle, widget: string}
      - {label: "СЕО Описание", name: description, widget: text}
      - {label: "СЕО Изображение", name: seoimage, widget: image}
      - { name: info, label: "Кратко", widget: text }
      - { name: body, label: "Описание", widget: markdown }
  - name: ourworks
    label: "Наши Работы"
    folder: site/content/our-works
    create: true
    fields:
      - { name: path, label: "URL путь" }
      - { name: title, label: "Название раздела" }
      - { name: image, label: "Изображение", widget: image }
      - {label: "СЕО Заголовок", name: seotitle, widget: string}
      - {label: "СЕО Описание", name: description, widget: text}
      - {label: "СЕО Изображение", name: image, widget: image}
      - {label: "Фон заголовка", name: image, widget: image}
      - { name: body, label: "Описание", widget: markdown }
      - label: "Подраздел"
        name: block
        widget: list
        fields:
          - {label: "Заголовок", name: title, widget: string}
          - {label: "Картинка", name: image, widget: image}
          - label: "Примеры работ"
            name: works
            widget: list
            fields:
              - {label: "СЕО подпись", name: alt, widget: string}
              - {label: "Картинка", name: image, widget: image}
